### PR TITLE
Relicense to MIT

### PR DESCRIPTION
**Pull request by unascribed**
* [x] @unascribed
* [x] @codewarrior0
* [x] @3TUSK

Please respond to this PR with something along the lines of "I [github user] consent to the relicensing of my contributions to the Correlated project under the MIT license."

### CODE REVIEW

**Comment by unascribed** [comment]
I @unascribed consent to the relicensing of my contributions to the Correlated project under the MIT license.

**Comment by codewarrior0** [comment]
I @codewarrior consent to the relicensing of my contributions to the Correlated project under the MIT license.

**Comment by 3TUSK** [comment]
I @3TUSK consent to the relicensing of my contributions to the Correlated project under the MIT license, or any of other license.

> Never thought that translation also counts.

**Comment by unascribed** [comment]
@3TUSK It's a contribution covered by the repository's license, so yes, it does. :P

**Pull request merged**
